# Generated by Django 4.2.2 on 2023-06-21 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userApp', '0002_posts_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='is_image',
        ),
    ]
