# Generated by Django 4.2.2 on 2023-06-20 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email_address', models.EmailField(max_length=50)),
                ('password', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=75)),
                ('full_name', models.CharField(max_length=100)),
                ('profile_image_url', models.URLField(blank=True)),
                ('bio', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
