# Generated by Django 4.2.2 on 2023-06-20 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login_register', '0003_alter_users_options_alter_users_managers_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='users',
            managers=[
            ],
        ),
    ]
