# Generated by Django 4.2.2 on 2023-06-25 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_register', '0005_remove_users_profile_image_url_users_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='profile_image',
            field=models.ImageField(blank=True, default='default_profile_pic/Default_pfp.jpg', upload_to='profile_images/'),
        ),
    ]
